import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;*/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oshin
 */
public class menu extends javax.swing.JFrame {
     private Connection con; 
     private Statement stat;
     private PreparedStatement prep;
     private ResultSet res;
     
    public menu() {
        initComponents();
        koneksi();
        update_tabelAnggota();
        update_tabelPelatih();
        update_tabelJadwal();
        lapangan();
        anggota();
        pelatih();
    }
    
            private void koneksi(){
                try {
                     Class.forName("com.mysql.jdbc.Driver");
                     con = DriverManager.getConnection(""+"jdbc:mysql://localhost:3306/tenisitup", "root", "");
                     stat = con.createStatement();
                     }catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    
            }
            
             private void bersihkan(){
            
            txtIdA.setText("");
            txtNamaA.setText("");  
            txtAlamatA.setText("");  
            txtIdA.requestFocus();
            }
     public final void update_tabelAnggota(){
         try{
             koneksi();
             String query = "Select * From anggota order by id_anggota";
             prep = con.prepareStatement(query);
             res = prep.executeQuery();
             tbAnggota.setModel(DbUtils.resultSetToTableModel(res));
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }finally
         {
             try{
                 res.close();
                 prep.close();
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
             }
         }
     }
     
      public final void update_tabelPelatih(){
         try{
             koneksi();
             String query = "Select * From pelatih order by id_pelatih";
             prep = con.prepareStatement(query);
             res = prep.executeQuery();
             tbPelatih.setModel(DbUtils.resultSetToTableModel(res));
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }finally
         {
             try{
                 res.close();
                 prep.close();
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
             }
         }
     }
      
       public final void update_tabelJadwal(){
         try{
             koneksi();
             String query = "Select jadwal.id_jadwal, jadwal.hari, lapangan.nama_lapangan, "
                     + "anggota.nama_anggota, pelatih.nama_pelatih  From jadwal,lapangan,pelatih,"
                     + "anggota where anggota.id_anggota=jadwal.id_anggota and "
                     + "lapangan.kode=jadwal.kode and pelatih.id_pelatih=jadwal.id_pelatih order by id_jadwal";
             prep = con.prepareStatement(query);
             res = prep.executeQuery();
             tbJadwal.setModel(DbUtils.resultSetToTableModel(res));
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }finally
         {
             try{
                 res.close();
                 prep.close();
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
             }
         }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAnggota = new javax.swing.JTable();
        tambahAnggota = new javax.swing.JButton();
        editAnggota = new javax.swing.JButton();
        hapusAnggota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaA = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatA = new javax.swing.JTextArea();
        txtIdA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPelatih = new javax.swing.JTable();
        tambahPelatih = new javax.swing.JButton();
        editPelatih = new javax.swing.JButton();
        hapusPelatih = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNamaP = new javax.swing.JTextField();
        lbId1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAlamatP = new javax.swing.JTextArea();
        txtIdP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbJadwal = new javax.swing.JTable();
        tambahJadwal = new javax.swing.JButton();
        editJadwal = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbEHari = new javax.swing.JComboBox();
        cmbELapangan = new javax.swing.JComboBox();
        cmbEAnggota = new javax.swing.JComboBox();
        cmbEPelatih = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtIdJ = new javax.swing.JTextField();
        hapusJadwal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KLUB TENIS ITUP");

        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAnggotaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAnggota);

        tambahAnggota.setText("Tambah");
        tambahAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAnggotaActionPerformed(evt);
            }
        });

        editAnggota.setText("Update");
        editAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAnggotaActionPerformed(evt);
            }
        });

        hapusAnggota.setText("Hapus");
        hapusAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusAnggotaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel3.setText("Id");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel4.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel5.setText("Alamat");

        lbId.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N

        txtAlamatA.setColumns(20);
        txtAlamatA.setRows(5);
        jScrollPane1.setViewportView(txtAlamatA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ubah Data Anggota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIdA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambahAnggota, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambahAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusAnggota)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jTabbedPane3.addTab("Anggota", jPanel5);

        tbPelatih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "Alamat"
            }
        ));
        tbPelatih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPelatihMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbPelatih);

        tambahPelatih.setText("Tambah");
        tambahPelatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPelatihActionPerformed(evt);
            }
        });

        editPelatih.setText("Update");
        editPelatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPelatihActionPerformed(evt);
            }
        });

        hapusPelatih.setText("Hapus");
        hapusPelatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelatihActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel6.setText("Id");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel7.setText("Nama");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel8.setText("Alamat");

        lbId1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N

        txtAlamatP.setColumns(20);
        txtAlamatP.setRows(5);
        jScrollPane4.setViewportView(txtAlamatP);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ubah Data Pelatih");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbId1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbId1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambahPelatih, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editPelatih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusPelatih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambahPelatih)
                        .addGap(18, 18, 18)
                        .addComponent(editPelatih)
                        .addGap(18, 18, 18)
                        .addComponent(hapusPelatih)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Pelatih", jPanel6);

        tbJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hari", "Lapangan", "Anggota", "Pelatih"
            }
        ));
        tbJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJadwalMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbJadwal);

        tambahJadwal.setText("Tambah");
        tambahJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahJadwalActionPerformed(evt);
            }
        });

        editJadwal.setText("Update");
        editJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJadwalActionPerformed(evt);
            }
        });

        jPanel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel10.setText("Hari");

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel11.setText("Lapangan");

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel12.setText("Anggota");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel13.setText("Pelatih");

        cmbEHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senin", "Rabu", "Jumat" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Ubah Data Pelatih");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel15.setText("Id Jadwal");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEHari, 0, 123, Short.MAX_VALUE)
                            .addComponent(cmbELapangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEPelatih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdJ))))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtIdJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbEHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbELapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbEAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbEPelatih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        hapusJadwal.setText("Hapus");
        hapusJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tambahJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambahJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(editJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(hapusJadwal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Jadwal", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(489, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{ depan l = new depan();
            l.setLayar(true);
        this.dispose();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tambahAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAnggotaActionPerformed
       try{ TambahAnggota ta = new TambahAnggota();
        ta.setLayar(true);
       this.dispose();
               }
       catch(Exception e)
       {
       JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_tambahAnggotaActionPerformed

    private void tambahPelatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPelatihActionPerformed
      try{  TambahPelatih tp = new TambahPelatih();
        tp.setLayar(true);
      this.dispose();}
      catch(Exception e)
      {
      JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_tambahPelatihActionPerformed

    private void tambahJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahJadwalActionPerformed
       try{ TambahJadwal tj = new TambahJadwal();
        tj.setLayar(true);
       this.dispose();}
       catch(Exception e)
       {
       JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_tambahJadwalActionPerformed

    private void hapusAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusAnggotaActionPerformed
        String sql = "delete from anggota where id_anggota=?";
        try{
            
            prep = con.prepareStatement(sql);
            prep.setString(1, txtIdA.getText());
            prep.execute();
                    
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
            this.dispose();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "keteraanan eror :"+e);
            }
        
        menu sv = new menu();
        sv.setLayar(true);
    }//GEN-LAST:event_hapusAnggotaActionPerformed

    private void hapusPelatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelatihActionPerformed
        String sql = "delete from pelatih where id_pelatih=?";
        try{
            
            prep = con.prepareStatement(sql);
            prep.setString(1, txtIdP.getText());
            prep.execute();
                    this.dispose();
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "keteraanan eror :"+e);
            }
        
        menu sv = new menu();
        sv.setLayar(true);
    }//GEN-LAST:event_hapusPelatihActionPerformed

    private void editJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJadwalActionPerformed
        try{
            String isi1 = txtIdJ.getText();
            Object isi2 = cmbEHari.getSelectedItem().toString();
            Object isi3 = cmbELapangan.getSelectedItem().toString();
            Object isi4 = cmbEAnggota.getSelectedItem().toString();
            Object isi5 = cmbEPelatih.getSelectedItem().toString();
        
            String sql = "Update jadwal set hari='"+isi2+"',kode='"+isi3+"',id_anggota='"+isi4+"',id_pelatih='"+isi5+"' where id_jadwal='"+isi1+"'";
            prep = con.prepareStatement(sql);
            prep.execute();
            bersihkan();
            JOptionPane.showMessageDialog(null, "Data sudah diupdate");
            this.dispose();   
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, "keteraanan eror :"+e);
            }
        
        menu sv = new menu();
        sv.setLayar(true);
        
    }//GEN-LAST:event_editJadwalActionPerformed

    private void editAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAnggotaActionPerformed
      try{
            String isi1 = txtIdA.getText();
            String isi2 = txtNamaA.getText();
            String isi3 = txtAlamatA.getText();
        
            String sql = "Update anggota set nama_anggota='"+isi2+"',alamat='"+isi3+"' where id_anggota='"+isi1+"'";
            prep = con.prepareStatement(sql);
            prep.execute();
            bersihkan();
            JOptionPane.showMessageDialog(null, "Data sudah diupdate");
            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "keteraanan eror :"+e);
        }
        menu sv = new menu();
        sv.setLayar(true);
    }//GEN-LAST:event_editAnggotaActionPerformed

    private void editPelatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPelatihActionPerformed
        try {
            String isi1 = txtIdP.getText();
            String isi2 = txtNamaP.getText();
            String isi3 = txtAlamatP.getText();

            String sql = "Update pelatih set nama_pelatih='" + isi2 + "',alamat='" + isi3 + "'where id_pelatih='"+isi1+"'";
            prep = con.prepareStatement(sql);
            prep.execute();
            this.dispose();
            JOptionPane.showMessageDialog(null, "Data sudah diupdate");
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "keteraanan eror :"+e);
        }
        menu sv = new menu();
        sv.setLayar(true);
    }//GEN-LAST:event_editPelatihActionPerformed

    private void tbAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAnggotaMouseClicked
            String isi1 = txtIdA.getText();
            String isi2 = txtNamaA.getText();
            String isi3 = txtAlamatA.getText();
            
            int baris = tbAnggota.getSelectedRow();
            txtIdA.setText(tbAnggota.getModel().getValueAt(baris, 0).toString());
            txtNamaA.setText(tbAnggota.getModel().getValueAt(baris, 1).toString());
            txtAlamatA.setText(tbAnggota.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbAnggotaMouseClicked

    private void tbPelatihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPelatihMouseClicked
            String isi1 = txtIdP.getText();
            String isi2 = txtNamaP.getText();
            String isi3 = txtAlamatP.getText();
            
            int baris = tbPelatih.getSelectedRow();
            txtIdP.setText(tbPelatih.getModel().getValueAt(baris, 0).toString());
            txtNamaP.setText(tbPelatih.getModel().getValueAt(baris, 1).toString());
            txtAlamatP.setText(tbPelatih.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbPelatihMouseClicked

    private void tbJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJadwalMouseClicked
            String isi1 = txtIdJ.getText();
            Object isi2 = cmbEHari.getSelectedItem();
            Object isi3 = cmbELapangan.getSelectedItem();
            Object isi4 = cmbEAnggota.getSelectedItem();
            Object isi5 = cmbEPelatih.getSelectedItem();
            
            int baris = tbJadwal.getSelectedRow();
            txtIdJ.setText(tbJadwal.getModel().getValueAt(baris, 0).toString());
            cmbEHari.setSelectedItem(tbJadwal.getModel().getValueAt(baris, 1).toString());
            cmbELapangan.setSelectedItem(tbJadwal.getModel().getValueAt(baris, 2).toString());
            cmbEAnggota.setSelectedItem(tbJadwal.getModel().getValueAt(baris, 3).toString());
            cmbEPelatih.setSelectedItem(tbJadwal.getModel().getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tbJadwalMouseClicked

    private void hapusJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusJadwalActionPerformed
        String sql = "delete from jadwal where id_jadwal=?";
        try{
            
            prep = con.prepareStatement(sql);
            prep.setString(1, txtIdJ.getText());
            prep.execute();
                    
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
           this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "keteraanan eror :"+e);
            }
        
        menu sv = new menu();
        sv.setLayar(true);
    }//GEN-LAST:event_hapusJadwalActionPerformed

    private void lapangan()
    {
        try{
            String sql = "select * from lapangan ";
            prep = con.prepareStatement(sql);
            res = prep.executeQuery();
            
            while (res.next()){
        
                cmbELapangan.addItem(res.getString("kode"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void anggota()
    {
        try{
            String sql = "select * from anggota";
            prep = con.prepareStatement(sql);
            res = prep.executeQuery();
            
            while (res.next()){
                cmbEAnggota.addItem(res.getString("id_anggota"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void pelatih()
    {
        try{
            String sql = "select * from pelatih";
            prep = con.prepareStatement(sql);
            res = prep.executeQuery();
            
            while (res.next()){
                cmbEPelatih.addItem(res.getString("id_pelatih"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    
    public void setLayar(boolean a){
        new menu().setVisible(a);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEAnggota;
    private javax.swing.JComboBox cmbEHari;
    private javax.swing.JComboBox cmbELapangan;
    private javax.swing.JComboBox cmbEPelatih;
    private javax.swing.JButton editAnggota;
    private javax.swing.JButton editJadwal;
    private javax.swing.JButton editPelatih;
    private javax.swing.JButton hapusAnggota;
    private javax.swing.JButton hapusJadwal;
    private javax.swing.JButton hapusPelatih;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbId1;
    private javax.swing.JButton tambahAnggota;
    private javax.swing.JButton tambahJadwal;
    private javax.swing.JButton tambahPelatih;
    private javax.swing.JTable tbAnggota;
    private javax.swing.JTable tbJadwal;
    private javax.swing.JTable tbPelatih;
    private javax.swing.JTextArea txtAlamatA;
    private javax.swing.JTextArea txtAlamatP;
    private javax.swing.JTextField txtIdA;
    private javax.swing.JTextField txtIdJ;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtNamaA;
    private javax.swing.JTextField txtNamaP;
    // End of variables declaration//GEN-END:variables
}
